### ISSUE TITLE
ETL not working for repeatable question group

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#55]
### Stack trace for an organisation with repeatable question groups below

OS: Ubuntu 22.04.1 x86_64 x86_64 x86_64 GNU/Linux

```
2023-07-04 10:49:26,507 ERROR [org.avniproject.etl.repository.sql.SqlFile] Cannot read file at /sql/etl/repeatableQG/subjectRepeatableQGObservations.sql
java.io.FileNotFoundException: class path resource [sql/etl/repeatableQG/subjectRepeatableQGObservations.sql] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:211)
        at org.avniproject.etl.repository.sql.SqlFile.readFile(SqlFile.java:16)
        at org.avniproject.etl.repository.sql.SqlFile.readSqlFile(SqlFile.java:25)
        at org.avniproject.etl.repository.sql.RepeatableQuestionGroupSyncSqlGenerator.getSql(RepeatableQuestionGroupSyncSqlGenerator.java:39)
        at org.avniproject.etl.repository.sql.RepeatableQuestionGroupSyncSqlGenerator.generateSql(RepeatableQuestionGroupSyncSqlGenerator.java:33)
        at org.avniproject.etl.repository.sync.RepeatableQGTransactionTablesSyncAction.lambda$perform$0(RepeatableQGTransactionTablesSyncAction.java:35)
        at org.avniproject.etl.repository.JdbcContextWrapper.wrap(JdbcContextWrapper.java:33)
        at org.avniproject.etl.repository.JdbcContextWrapper.wrapInOrgContext(JdbcContextWrapper.java:21)
        at org.avniproject.etl.repository.JdbcContextWrapper.runInOrgContext(JdbcContextWrapper.java:10)
        at org.avniproject.etl.repository.sync.RepeatableQGTransactionTablesSyncAction.perform(RepeatableQGTransactionTablesSyncAction.java:34)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
        at org.avniproject.etl.repository.sync.RepeatableQGTransactionTablesSyncAction$$SpringCGLIB$$0.perform(<generated>)
        at org.avniproject.etl.repository.sync.EntityRepository.lambda$saveEntities$0(EntityRepository.java:37)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.avniproject.etl.repository.sync.EntityRepository.saveEntities(EntityRepository.java:36)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
...
```

**Comment by vinayvenu** [comment]
Taking care as part of the regular story.
